### ISSUE TITLE
Implement fire trace gas emissions in FATES

### ISSUE THREAD

**Issue by rosiealice** [NGEET/fates#1088]
There are a couple of issues related to this already. One which has evolved into a discussion of how to allow FATES and the fire emissions from CTSM to the atmosphere to operate concurrently [here](https://github.com/ESCOMP/CTSM/issues/1045) and another looking at the combustion of C and N (#485) 

Here I wanted to focus on **actually calculating the fire emissions** in the context of FATES. 

In the original SPITFIRE code, the emissions were calculated as the 'emissions factor' per species of trace gas, multiplied by the carbon burned (see exceprt from the original Thonicke 2010 SPITFIRE paper:

![Image](https://github.com/NorESMhub/CTSM/assets/12954691/1cd37a2a-940c-4a75-be3b-33fa222704c0)

For refererence, a link to whole Thonicke SPITFIRE paper is  [here](https://bg.copernicus.org/articles/7/1991/2010/bg-7-1991-2010.pdf)

The emission factors are PFT specific, as described below. Their provenance was updated for CLM5. 

![Image](https://github.com/NorESMhub/CTSM/assets/12954691/8444023b-f934-4110-a186-19f7fa1d6774)

Also for reference, this is the table of EFs from the  original SPITFIRE model, depicted in their table 1:

![Image](https://github.com/NorESMhub/CTSM/assets/12954691/499ef915-a634-4de1-a406-a5d14a578e12)

It is worth noting that the CLM5 fire model works in a similar way 
https://github.com/ESCOMP/CTSM/blob/2e2434d10e35404be5284022270f474d50d2db26/src/biogeochem/CNFireEmissionsMod.F90#L292

It seems like as of the CLM5 release, actually getting the emissions into the atmosphere was a 'research topic' (this from the CLM5 paper). 

![Image](https://github.com/NorESMhub/CTSM/assets/12954691/587b3fa1-feb0-4f5d-b4d4-d37062d96461)

I guess that Maria vM has probably continued with this effort since the release, Someone can update this thread if they know the status of that. It might be a good idea to involve her in this discussion.  The canopy injection height calculations happen here. The emission heights are hard-coded:  
https://github.com/ESCOMP/CTSM/blob/2e2434d10e35404be5284022270f474d50d2db26/src/biogeochem/CNFireEmissionsMod.F90#L324

There are potential some  duplication issues that we would need to navigate here. My suspicion is that we should just have FATES handle its own emissions factors and code. The  amount of actual physics involved is very small (it's only really 2-3 very straightforward equations) and (most importantly) the principle of FATES is that it handles everything with a PFT identity. Having to map a new PFT back onto an existing set of fire emissions would be a world of pain in the long run when we wanted to introduce new things into FATES. Plus there is a lot of potentially interesting science to be done with the links between e.g. plant trait and their emissions which we don't want to rule out. 

Anyone have any thoughts on this? Here is a strawman list of tasks.. 

```[tasklist]
### Tasks
- [ ] Create PFT x trace gas class emission factor variable in parameter file.
- [ ] Create injection height parameter (PFT dimension)
- [ ] Create dimension to handle the number of emission species. 
- [ ] Create function to calculate emissions in SPITFIRE code.
- [ ] Modify FATES interface to pass OUT the emission factors and their injection height profile
- [ ] Adjust HLM code to accept these fluxes in the case of FATES
- [ ] Create appropriate FATES history variables to report fluxes. 
```

**Comment by XiulinGao** [comment]
Hi Rosie, thank you for bringing this up! I am interested in developing this since one of the projects I am currently working on with @lmkueppers is specifically about wildfire emissions in California. I just found that the CLM fire emission variables cannot be passed to FATES (guess because it's handled by its own fire model that conflicts with FATES-SPITFIRE). Olson points me to this thread here. I am sure how much model developing effort is expected for this, but I'd like to have a conversation about this with you and Lara and anyone that is interested  sometimes later if you are still interested!

Xiulin
